version: "3.9"

services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    depends_on:
      - "db"
    environment:
      - DATABASE_URL
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - MAILJET_API_KEY
      - MAILJET_API_SECRET
      - MAILJET_TEMPLATE_BOOKING
      - MAILJET_TEMPLATE_VALIDATE
      - MAILJET_TEMPLATE_REFUSAL
      - MAILJET_SENDER

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD:
    ports:
      - 9999:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  default:
    name: debian_net-caddy
    external: true
