import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const teachers = trpc.teacher.getAll.useQuery();
  const [name, setName] = useState("");

  const createTeacher = trpc.teacher.create.useMutation({
    onSuccess() {
      teachers.refetch();
    },
  });

  const handleCreate = async () => {
    createTeacher.mutate({ name });
  };

  return (
    <>
      <Head>
        <title>Formatteurs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input
        type="text"
        value={name}
        onChange={(event) => setName(event.target.value)}
        className="border-2 border-black"
      />
      <button onClick={handleCreate}>Créer un prof</button>
    </>
  );
};

export default Home;
