import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.teacher.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Formateurs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Formateurs
      {data?.map((t) => (
        <div key={t.id}>{t.name}</div>
      ))}
    </>
  );
};

export default Home;
