import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { trpc } from "../../utils/trpc";

const Invite: NextPage = () => {
  const { data, isLoading, refetch } = trpc.teacher.getAll.useQuery();

  const createTeacher = trpc.teacher.create.useMutation({
    onSuccess() {
      refetch();
    },
  });
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleCreate = async () => {
    createTeacher.mutate({ name, password, email });
  };

  return (
    <>
      <Head>
        <title>Formateurs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Formateurs
      {data?.map((t) => (
        <div key={t.id}>{t.name}</div>
      ))}
      <label>
        Nom
        <input
          className="border-2 border-black"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
      </label>
      <br />
      <label>
        email
        <input
          className="border-2 border-black"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
      </label>
      <br />
      <label>
        mot de passe
        <input
          value={password}
          className="border-2 border-black"
          type="password"
          onChange={(e) => setPassword(e.target.value)}
        />
      </label>
      <button onClick={handleCreate}>Inviter</button>
    </>
  );
};

export default Invite;
